name: Run Unit Testing

on:
  push:
    branches: [ main ]
    paths-ignore: [ 'public/**', '*.md' ]

  pull_request:
    paths-ignore: [ 'public/**', '*.md' ]

jobs:
  linux_tests:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: true
      matrix:
        php: [ '7.4', '8.0' ]
        laravel: [ 7.*, 8.* ]
        dependency-version: [ prefer-lowest, prefer-stable ]

    name: PHP ${{ matrix.php }} - LARAVEL ${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-progress

      - name: Execute Tests
        run: vendor/bin/phpunit --verbose --colors=always
