name: Run Unit Testing

on:
  push:
    branches: [ main ]
    paths-ignore: [ 'public/**', '*.md' ]

  pull_request:
    paths-ignore: [ 'public/**', '*.md' ]

jobs:
  linux_tests:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: true
      matrix:
        php: [ '7.4', '8.0' ]
        stability: [ prefer-lowest, prefer-stable ]
        laravel: [ 7.*, 8.*, dev-master ]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, sqlite3, pdo_sqlite
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress ${{ matrix.flags }}

      - name: Execute Tests
        run: vendor/bin/phpunit --verbose --colors=always
